package com.tneciv.dockerboot.dao;

import com.tneciv.dockerboot.entity.Boot;
import com.tneciv.dockerboot.entity.BootExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BootMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot
     *
     * @mbg.generated
     */
    long countByExample(BootExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot
     *
     * @mbg.generated
     */
    int deleteByExample(BootExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot
     *
     * @mbg.generated
     */
    int insert(Boot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot
     *
     * @mbg.generated
     */
    int insertSelective(Boot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot
     *
     * @mbg.generated
     */
    List<Boot> selectByExample(BootExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot
     *
     * @mbg.generated
     */
    Boot selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Boot record, @Param("example") BootExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Boot record, @Param("example") BootExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Boot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table boot
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Boot record);
}